import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";
import ReduxProvider from "@/components/layout/ReduxProvider";

const Degular = localFont({
  src: [
    {
      path: "../fonts/DegularDisplay-Light.otf",
      weight: "300",
      style: "normal",
    },
    {
      path: "../fonts/DegularDisplay-Regular.otf",
      weight: "400",
      style: "normal",
    },
    {
      path: "../fonts/DegularDisplay-Medium.otf",
      weight: "500",
      style: "normal",
    },
    {
      path: "../fonts/DegularDisplay-Semibold.otf",
      weight: "600",
      style: "normal",
    },
    {
      path: "../fonts/DegularDisplay-Bold.otf",
      weight: "700",
      style: "normal",
    },
  ],
  variable: "--degular-font",
  display: "swap",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${Degular.variable} antialiased`}>
        <ReduxProvider>{children}</ReduxProvider>
      </body>
    </html>
  );
}
